// This file is auto-generated by convex dev
// Run `npx convex dev` to generate the actual API types
export const api = {
  media: {
    listMedia: {} as any,
    listMediaByType: {} as any,
  },
};
