// This file is auto-generated by convex dev
// Run `npx convex dev` to generate the actual server types

export const query = (args: any) => args;
export const mutation = (args: any) => args;
export const action = (args: any) => args;
